### PR TITLE
Getting 3D visualizations working again

### LINKED ISSUE #83: 3D Plot in Chapter 5 not rendering
Nothing I do seems to affect the 3D scatter plot in chapter 5. Something is failing silently...?

It's saved in `source/img/classification1/`, so it persists between builds even if the build fails. So it still looks OK (but the colours are wrong in the plot -- malignant is a light blue (in the rest of the chp it is orange)).

I'm moving on -- this is important to fix at some point, but doesn't need to be fixed for the first run of the course.

### LINKED ISSUE #127: Add plotly to the docker image
I think plotly may be missing. The pre-rendered images from when the MDS students were doing their pass are still committed though, and they're fine, so no need to do this right now.

### PR DESCRIPTION
**Pull request by trevorcampbell**
- Closes #127 
- Closes #83 

One potential issue: I see
```
/home/jovyan/source/classification1.md:786: WARNING: skipping unknown output mime type: application/vnd.plotly.v1+json [mystnb.unknown_mime_type]
```

@joelostblom if you want you can make similar viz adjustments to these new 3d figs that you made previously

In order to test this, just run the docker container interactively (instead of using `build_html.sh`), install `plotly`, and run `jupyter-book build source`.

NB: we will almost certainly have to have a build flag check for the PDF build and use a stored png version of these instead, but we can cross that bridge when we get to it

### CODE REVIEW

**Comment by trevorcampbell** [comment]
Let's not merge this until we merge #241 , so that we can use this PR as a test run for that new workflow

**Review by joelostblom — APPROVED** [review]
Nicely done, these changes look great and show up as expected in the rendered book!

Based on https://github.com/executablebooks/jupyter-book/issues/1950, it seems like that warning should not be an issue and can be either suppressed or the plotly rendering engine can be switch to an iframe https://github.com/executablebooks/jupyter-book/issues/2041

I found different syntax for how to enter the container interactively, so for reference this is what I used `docker container run -it --rm -v $(pwd):/home/jovyan ubcdsci/py-intro-to-ds:20230831171718ddf538 /bin/bash`

>  if you want you can make similar viz adjustments to these new 3d figs that you made previously

Hmm,I am not sure which changes you are referring to here.

**Comment by trevorcampbell** [comment]
> Hmm,I am not sure which changes you are referring to here.

Just the various syntax formatting stuff you did. It's really unimportant, because all the code is hidden anyway.

**Comment by trevorcampbell** [comment]
> I found different syntax for how to enter the container interactively, so for reference this is what I used docker container run -it --rm -v $(pwd):/home/jovyan ubcdsci/py-intro-to-ds:20230831171718ddf538 /bin/bash

No need for `container` -- you can just do:

```
 docker run -it --rm -v $(pwd):/home/jovyan ubcdsci/py-intro-to-ds:20230831171718ddf538 /bin/bash
```

**Comment by trevorcampbell** [comment]
I'm going to close and re-open this to try to trigger the new workflow from #241

**Comment by joelostblom** [comment]
> Just the various syntax formatting stuff you did. It's really unimportant, because all the code is hidden anyway.

Ah I see, I don't think that applies here since it was mostly altair-specific.

**Comment by trevorcampbell** [comment]
New github actions workflow is working properly, but it will re-build the image on every change to the PR. I've now edited the workflow in [e3701aa](https://github.com/UBC-DSCI/introduction-to-datascience-python/commit/e3701aaae671f9766d82de9a58c724c590b87979) so that it should only run when the Dockerfile itself is changed, but I'm going to push an empty commit here to test it.

**Comment by trevorcampbell** [comment]
OK, I've got the new workflow working properly. I force-pushed removal of a bunch of garbage commits while debugging, and I'm merging this now.

**Pull request merged**
